name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: my-app
  ECR_REGISTRY: 514661753203.dkr.ecr.us-east-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # 🟢 Build Docker Image
    - name: Build
      run: docker build -t my-app .

    # 🟡 Trivy Scan (ALLOW HIGH, BLOCK ONLY CRITICAL)
    - name: Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-app
        severity: CRITICAL
        exit-code: 1

    # 🟢 Configure AWS
    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: ${{ env.AWS_REGION }}

    # 🟢 Login to ECR
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $
